name: Build & Publish Docker Image

on:
 push:
 workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226
      - name: Docker Login
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Get Version
        run: python -c "from src.deploykit_server import __version__; print('VERSION=' + __version__)" >> $"$GITHUB_OUTPUT"
        id: version
      - name: Build & Push
        uses: docker/build-push-action@0565240e2d4ab88bba5387d719585280857ece09
        with:
          context: .
          push: true
          tags: ghcr.io/luotianyi-dev/deploykit,ghcr.io/luotianyi-dev/deploykit:${{ steps.version.outputs.VERSION }}
          build-args: |
            IMAGE_VERSION=${{ steps.version.outputs.VERSION }}
